project:
  type: website

website:
  title: "GIS4Epidemiology"
  image: "images/logo1.png"
  favicon: "images/logo.png"
  page-navigation: true
  navbar:
    left:
      - text: Home
        href: index.qmd
        
      - text: Session One
        href: session1.qmd
        menu:
          - text: Session 1A
            href: session1a-foundational-concepts.qmd
          - text: Session 1B
            href: session1b-intro-sds.qmd
          - text: Session 1C
            href: session1c-investigate-outbreak.qmd
            
      - text: Session Two
        href: session2.qmd
        menu:
          - text: Session 2A
            href: session2a-spatial-data-vis.qmd
          - text: Session 2B
            href: session2b-case-studies.qmd
          - text: Session 2C      
            href: session2c-hands-on.qmd
            
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



